name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
        - run: npm ci
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        
    create-github-release:
      name: Create GitHub Release
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Create Release
          run: gh release create ${{ github.ref }} --generate-notes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

